export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const SET_SUB_CATEGORY = "SET_SUB_CATEGORY";
export const DELETE_SUB_CATEGORY = "DELETE_SUB_CATEGORY";
export const POST_SUB_CATEGORY = "POST_SUB_CATEGORY";
export const SHOW_SNAKCBAR = "SHOW_SNAKCBAR";
export const CLOSE_SNAKCBAR = "CLOSE_SNAKCBAR";
